name: mogu_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  flutter_svg: ^2.0.9
  image_picker: ^0.8.7+3
  file_picker: ^5.0.1
  intl: ^0.17.0
  geocoding: ^2.0.3
  flutter_naver_map: ^1.2.3+1
  geolocator: ^9.0.2
  permission_handler: ^11.3.1
  webview_flutter: ^4.0.0
  google_mobile_ads: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/Mogulogo.png
  - assets/icons/post_create_button.svg
  - assets/icons/selected_home.svg
  - assets/icons/selected_chat.svg
  - assets/icons/selected_history.svg
  - assets/icons/selected_my_page.svg
  - assets/icons/unselected_home.svg
  - assets/icons/unselected_chat.svg
  - assets/icons/unselected_history.svg
  - assets/icons/unselected_my_page.svg
  - assets/icons/search_filter.svg
  - assets/icons/unselected_member_management.svg
  - assets/icons/selected_member_management.svg
  - assets/icons/selected_complaint_management.svg
  - assets/icons/unselected_complaint_management.svg

flutter_native_splash:
    image: assets/Mogulogo.png
    android: true
    ios: true

